import os

TENSORBOARD_DIR = 'tensorboard/'

GAMMA = 0.98
BATCH_SIZE = 32
RW_EPS = 0.02

ALGORITHM_SEED = 2**3-1

#DQN
MAX_DQN_ITERATIONS = 10000
DQN_LEARNING_RATE = 1e-3
MIN_DQN_LEARNING_RATE = 1e-3
TARGET_NETWORK_UPDATE_RATE = 2000
REPLAY_BUFFER_START_SIZE = 5000


EPSILON_INITIAL = 1.0
MIN_EPSILON = 0.01
EPSILON_RENEWAL_RATE = 5000
EPSILON_RENEWAL_FACTOR = 0.9

TIME_SEQUENCE_SIZE = 10

DEFAULT_SAVE_MODELS_PATH = os.getcwd()+"/algorithms/saved_models/"
